# Generated by Django 5.2 on 2025-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='display_mode',
            field=models.CharField(default='light', max_length=6),
        ),
    ]
