# Generated by Django 5.2 on 2025-04-14 11:23

import barcodeRec.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeRec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=barcodeRec.models.upload_to_fixed_name),
        ),
    ]
