# Generated by Django 5.2 on 2025-05-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcodeRec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.CharField(default='/static/missingCover.png', max_length=255),
        ),
    ]
